# Generated by Django 6.1.1 on 2026-10-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='about/')),
                ('daily_visitors', models.IntegerField(default=0)),
                ('stories', models.IntegerField(default=0)),
                ('recipes', models.IntegerField(default=0)),
                ('users', models.IntegerField(default=0)),
            ],
        ),
    ]
